# Site settings
title: Spencer Walker-Fooks
twitter_username: 3DSpencer
name: Spencer Walker-Fooks

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/SpencerWF
 - title: LinkedIn
   url: https://www.linkedin.com/in/spencer-walker-fooks

#Any buzzword skills you want to include
skills:
 - Pylint
 - Python
 - Git
 - UnitTest
 - Test-Driven Development
 - Embedded Software Development
 - Wireless Sensor Networks
 - Embedded System Design
 - I2C, SPI, UART communication protocals
 - Computer Vision Development (OpenCV)

#Work experience is required
roles:
 - title: Advisor, Contract
   start: Dec 2017
   end: Ongoing
   employer: GulfGCD, Oman
• Working with the founders in business development, and strategy for the very beginning of a start-up
company.
• Developing and incorporating new technologies into business flow.
 - title: Product Lead
   start: Sep 2016
   end: May 2018
   employer: BioCarbon Engineering
   description: 
• Started working with the firm as a Mechatronics Engineer, collaborating with a close-knit engineering team to develop custom drone and payload solutions at this ecosystem restoration start-up;
• Promoted to Product Lead in 2017, responsible for managing the design, development and timeline of the engineering team in developing new technologies for the company;
• Custom payload solutions required embedded python development on Raspberry Pi and Atmel Microcontrollers;
• Development of Computer Vision Solutions (OpenCV3) for payload decision making;
• Communicate with clients and the sales team to determine what technologies clients would value and ensuring they align with the requirements of the plant science team.
 - title: Owner, CAD Developer
   start: Jan 2014
   end: May 2016
   employer: Self-Employed
   description: 
• Designed, printed and sold parts for engineering students using a Solidoodle 2 3D printer;
• Managed all aspects of the business, from financing and business development through to marketing and customer relations, as well as conducting competitor analysis.
 - title: Engineering Trainee
   start: Nov 2014
   end: Dec 2014
   employer: Comino Management Services Pty Ltd
   description: 
• Upgraded and managed a dragline motors database for one of the company’s clients (Database Management);
• Gained an understanding of the desired outcome of the database to ensure the database was maintained in the most effective way and that the use of the database by engineers was most effective.
 - title: Electrician's Assistant
   start: Nov 2013
   end: Dec 2013
   employer: Protech Power
   description:
• Repurposed a number of fixed power supplies (AC and DC) for testing purposes on other projects;
• Setup fixed power supplies together so that they could be used in coordination, developing a variable power
supply (VPS) with a much larger current flow capability than a conventional VPS;
• Collaborated with Senior Engineers to ensure full insulation and appropriate labelling was used where required.
 - title: Trademan's Assistant
   start: March 2011
   end: Dec 2011
   employer: Protech Power
   description:
• Worked with the electricians to conduct Protection Relay Testing, Installation of Gas Insulated Switchgear,
Cable Termination, Cable Tray Installation, Cable Identification and Labelling for train line demountables;
• Liaised with a team of 4 engineers and 20 tradesmen to ensure that work is coordinated effectively;
• Coordinated with Electrical Engineers to write an automated system of protection relay test plans for a Doble
F6150 ProTest program, learning a new programming interface to achieve the desired outcomes;

#Education is required
education:
 - level: Bachelor of Engineering (B.Eng.)
   date: 2016
   subject: Mechatronics, Robotics, and Automation Engineering
   school: University of Queensland
 - level: Certificate
   date: 2016
   subject: New Ventures Leadership
   school: Massachusetts Institute of Technology

edx.org:
   courses:
    - title: Blockchain for Business
      link: https://www.edx.org/course/blockchain-business-introduction-linuxfoundationx-lfs171x

udemy:
   courses:
    - title: Complete Python Bootcamp
      link: https://www.udemy.com/complete-python-bootcamp/learn/v4/overview
   courses:
    - title: Master Computer Vision OpenCV3 in Python & Machine Learning


#Github Projects
Github:
 - SpencerWF/METR4810_Spencer
 - SpencerWF/Elec4630_Spencer
 - SpencerWF/CustomFunctions


theme: jekyll-theme-tactile
